In [1]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [25]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [39]:
np.random.rand(5,5)

array([[0.69061712, 0.99261984, 0.5883827 , 0.25302357, 0.06848212],
       [0.30404604, 0.41203186, 0.46862049, 0.33998037, 0.88332407],
       [0.21256229, 0.83981053, 0.95120143, 0.86560892, 0.75552636],
       [0.55653596, 0.43591737, 0.13879864, 0.15299859, 0.58319741],
       [0.56088616, 0.29566829, 0.91645531, 0.11425664, 0.77959062]])

In [41]:
np.random.randn(4,4)

array([[-0.75740734, -0.11704871,  0.21139447, -0.25191643],
       [ 0.45898945, -0.36833365, -0.30322122,  1.51478434],
       [-0.41628144, -0.88118047, -0.18472156,  0.65176629],
       [ 1.0485205 , -0.31330586,  0.59624084,  0.03438583]])

In [44]:
np.random.randint(1,100,10)

array([34, 79, 67, 93, 64, 15,  5, 24, 27, 81])

In [46]:
arr = np.arange(25)

ranarr = np.random.randint(0,50,10)

arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
ranarr.max()


45

In [50]:
ranarr.min()

0

In [52]:
ranarr.argmax()

3

In [54]:
arr.shape

(25,)

In [56]:
arr.dtype

dtype('int64')

In [59]:
from numpy.random import randint
randint(2,10)


8