In [2]:
import numpy as np

In [13]:
arr = np.arange(0,11)

In [7]:
arr[8]

8

In [9]:
arr[1:5]

array([1, 2, 3, 4])

In [12]:
arr[0:5] = 99

In [14]:
arr = np.arange(0,11)

In [16]:
slice_of_arr = arr[0:6]

In [17]:
slice_of_arr[:] = 99

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy[:] = 44

In [23]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [30]:
arr_2d[1][1]

25

In [33]:
arr_2d[1,1]

25

In [37]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [39]:
arr = np.arange(1,11)

In [44]:
bool_arr = arr > 5 

In [46]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [48]:
arr[arr<3]

array([1, 2])

In [53]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])